-- *** SqlDbx Personal Edition ***
-- !!! Not licensed for commercial use beyound 90 days evaluation period !!!
-- For version limitations please check http://www.sqldbx.com/personal_edition.htm
-- Number of queries executed: 1011, number of rows retrieved: 7848
SELECT * FROM PESSOASFORDEV 
SELECT TOP 5 CPF FROM PESSOASFORDEV ORDER BY NEWID()
SELECT count(1) FROM PESSOASFORDEV
SELECT count(1), nome FROM PESSOASFORDEV GROUP BY nome HAVING count(1)>1


SELECT * FROM EMPRESAFORDEV
SELECT TOP 5 CNPJ FROM EMPRESAFORDEV ORDER BY NEWID()
SELECT count(1) FROM EMPRESAFORDEV
SELECT count(1), nome FROM EMPRESAFORDEV GROUP BY nome HAVING count(1)>1

SELECT * FROM VEICULOSFORDEV
SELECT TOP 5 RENAVAM FROM VEICULOSFORDEV ORDER BY NEWID()
SELECT count(1) FROM VEICULOSFORDEV
SELECT count(1), MODELO FROM VEICULOSFORDEV GROUP BY MODELO HAVING count(1)>1

/*
CREATE TABLE PESSOASFORDEV (
NOME  VARCHAR(2000)  DEFAULT '' NOT NULL , 
IDADE  INTEGER  DEFAULT 0 NOT NULL , 
CPF  VARCHAR(12)  DEFAULT '' NOT NULL , 
RG  VARCHAR(12)  DEFAULT '' NOT NULL , 
DATANASCIMENTO  VARCHAR(10)  DEFAULT '' NOT NULL , 
SEXO  VARCHAR(20)  DEFAULT 'Masculino' NOT NULL , 
SIGNO  VARCHAR(30)  DEFAULT '' NOT NULL , 
MAE  VARCHAR(2000)  DEFAULT '' NOT NULL , 
PAI  VARCHAR(2000)  DEFAULT '' NOT NULL , 
EMAIL  VARCHAR(500)  DEFAULT '' NOT NULL , 
SENHA  VARCHAR(50)  DEFAULT '' NOT NULL , 
CEP  VARCHAR(8)  DEFAULT '' NOT NULL , 
ENDERECO  VARCHAR(1000)  DEFAULT '' NOT NULL , 
NUMERO  INTEGER  DEFAULT 0 NOT NULL , 
BAIRRO  VARCHAR(500)  DEFAULT '' NOT NULL , 
CIDADE  VARCHAR(1000)  DEFAULT '' NOT NULL , 
ESTADO  CHAR(2)  DEFAULT 'MG' NOT NULL , 
TELEFONEFIXO  VARCHAR(50)  DEFAULT '' NOT NULL , 
CELULAR  VARCHAR(50)  DEFAULT '' NOT NULL , 
ALTURA  VARCHAR(10)  DEFAULT '' NOT NULL , 
PESO  INTEGER  DEFAULT 0 NOT NULL , 
TIPOSANGUINEO  VARCHAR(3)  DEFAULT '' NOT NULL , 
CORFAVORITA  VARCHAR(30)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CPF  )
)











CREATE TABLE EMPRESAFORDEV (
NOME  VARCHAR(200) , 
CNPJ  VARCHAR(15)  DEFAULT '' NOT NULL , 
IE  VARCHAR(50)  DEFAULT '' NOT NULL , 
DATAABERTURA  VARCHAR(12)  DEFAULT '' NOT NULL , 
SITE  VARCHAR(500)  DEFAULT '' NOT NULL , 
EMAIL  VARCHAR(500)  DEFAULT '' NOT NULL , 
CEP  VARCHAR(10)  DEFAULT '' NOT NULL , 
ENDERECO  VARCHAR(100)  DEFAULT '' NOT NULL , 
NUMERO  VARCHAR(20)  DEFAULT '' NOT NULL , 
BAIRRO  VARCHAR(500)  DEFAULT '' NOT NULL , 
CIDADE  VARCHAR(500)  DEFAULT '' NOT NULL , 
ESTADO  CHAR(3)  DEFAULT 'SP' NOT NULL , 
TELEFONEFIXO  VARCHAR(30)  DEFAULT '' NOT NULL , 
CELULAR  VARCHAR(30)  DEFAULT '' NOT NULL 
,  PRIMARY KEY ( CNPJ  )
)

CREATE TABLE VEICULOSFORDEV (
MARCA  VARCHAR(300)  DEFAULT '' NOT NULL , 
MODELO  VARCHAR(300)  DEFAULT '' NOT NULL , 
ANO  VARCHAR(10)  DEFAULT '' NOT NULL , 
RENAVAM  VARCHAR(30)  DEFAULT '' NOT NULL , 
PLACAVEICULO  VARCHAR(20)  DEFAULT '' NOT NULL , 
COR  VARCHAR(50)  DEFAULT '' NOT NULL ,
PRIMARY KEY (RENAVAM)
)
*/